### ISSUE TITLE
QLive2D编译后运行时崩溃

### ISSUE THREAD

**Issue by Longxr** [6ziv/Custom-Samples#1]
![image](https://user-images.githubusercontent.com/15936923/86106479-2fcced80-baf3-11ea-913d-12fc27d23570.png)
编译环境Qt5.12.5 MSVC2017 64bit + VS2019
已经将Resources、settings.conf、bass.dll都拷贝到exe运行目录了。

**Comment by 6ziv** [comment]
fixed.
程序从工作目录的相对路径加载资源，这不一定与程序所在目录相同，可能导致资源加载失败。
通过在程序开始时把工作目录设置为程序所在目录解决。
（同时旧的程序中有一些其它的之前没能看到的遗留问题，请更新至最新代码再进行编译）

**Comment by Longxr** [comment]
更新后拷贝资源文件到程序运行目录下可以正常运行，验证已修复
